export type LegalDocType = 'disclaimer' | 'terms' | 'privacy' | 'contact';

export interface LegalDocItem {
  id: LegalDocType;
  title: string;
  effectiveDate: string;
  content: string;
}

export const DISCLAIMER_CONTENT = `# Disclaimer

**Effective Date:** September 2026

Welcome to **Astronava**. Please read this Disclaimer carefully before using our website and services.

By accessing or using Astronava, you acknowledge that you have read, understood, and agreed to this Disclaimer.

---

# 1. Informational and Educational Purposes Only

Astronava provides Vedic astrology tools, birth chart analysis, Kundali Milan (Match Finder), gemstone recommendations, articles, and other astrology-related content for **informational and educational purposes only**.

The content available on this website is intended to help users understand traditional Vedic astrology principles and should not be interpreted as factual certainty or guaranteed outcomes.

---

# 2. No Professional Advice

The information provided on Astronava does **not** constitute:

* Medical advice
* Legal advice
* Financial or investment advice
* Psychological or mental health advice
* Professional counselling
* Any other licensed professional service

Always consult an appropriately qualified professional before making decisions regarding your health, finances, legal matters, relationships, or other important aspects of life.

---

## Emergency Mental Health Notice

Astronava is **not** a crisis intervention service, mental health provider, or emergency support service.

If you are experiencing emotional distress, thoughts of self-harm, suicidal thoughts, or believe you may be in immediate danger, **do not rely on this website or any astrological guidance**. Please seek immediate assistance from your local emergency services, a qualified mental health professional, or a trusted family member or friend.

If you believe someone else may be at immediate risk, contact your local emergency services without delay.

The content and services provided by Astronava are **not intended to diagnose, treat, or prevent any mental health condition**, and should never be used as a substitute for professional medical or psychological care.

---

# 3. Nature of Astrology

Astrology is a traditional belief system based on historical and cultural practices.

Astrological interpretations are subjective and may vary between practitioners, schools of thought, and calculation methods.

Astronava does not claim that astrology is scientifically proven or universally accepted.

---

# 4. Accuracy of Results

Astrological reports generated by Astronava are based entirely on the birth information provided by users.

The accuracy of any report depends upon the accuracy and completeness of the information entered.

Astronava cannot verify the correctness of user-submitted birth details and therefore cannot guarantee the accuracy of any generated report.

---

# 5. No Guarantees

Astronava makes no representations or warranties regarding:

* The accuracy of predictions
* Future events or outcomes
* Compatibility results
* Gemstone recommendations
* Remedies or suggestions
* Any decisions made based on our content

Individual experiences may vary, and no outcome is guaranteed.

---

# 6. User Responsibility

You are solely responsible for how you interpret and use the information provided on this website.

Any decisions made based on astrological reports or other content are entirely your own responsibility.

Astronava shall not be responsible for any loss, damage, or consequences arising from reliance on the information available through this website.

---

# 7. Third-Party Content and Services

Our website may include links to third-party websites or rely on third-party services such as hosting, analytics, or cloud infrastructure.

Astronava does not control or endorse third-party websites and is not responsible for their content, availability, security, or privacy practices.

---

# 8. Limitation of Liability

To the fullest extent permitted by applicable law, Astronava, its owners, developers, contributors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from:

* Use of the website
* Reliance on astrological reports or interpretations
* Technical errors or interruptions
* Temporary or permanent unavailability of services
* User-submitted information

Your use of Astronava is entirely at your own risk.

---

# 9. Changes to This Disclaimer

We reserve the right to update or modify this Disclaimer at any time without prior notice.

Any changes will become effective immediately upon publication on this page.

---

# 10. Contact Us

If you have any questions regarding this Disclaimer, please contact us:

**Email:** [himaaghna@gmail.com](mailto:himaaghna@gmail.com)

**Website:** https://astronava.vercel.app

---

By using Astronava, you acknowledge that you have read, understood, and agreed to this Disclaimer.`;

export const TERMS_AND_CONDITIONS_CONTENT = `# Terms & Conditions

**Effective Date:** September 2026

Welcome to **Astronava** ("Astronava", "we", "our", or "us").

These Terms & Conditions ("Terms") govern your access to and use of the Astronava website and its services. By accessing or using our website, you agree to be bound by these Terms. If you do not agree with these Terms, please discontinue use of the website.

---

# 1. About Astronava

Astronava is an online platform that provides Vedic astrology tools, educational resources, birth chart analysis, Kundali Milan (Match Finder), gemstone recommendations, and other astrology-related content based on traditional Vedic astrology principles.

The information and services provided on this website are intended for informational and educational purposes only.

---

# 2. Acceptance of Terms

By using Astronava, you confirm that:

* You are at least 13 years of age or are using the website under appropriate parental or guardian supervision.
* You have the legal capacity to agree to these Terms.
* You will use the website in accordance with all applicable laws and regulations.

---

# 3. User Responsibilities

When using Astronava, you agree to:

* Provide accurate birth information where required.
* Use the website only for lawful purposes.
* Refrain from attempting to gain unauthorized access to our systems.
* Not interfere with or disrupt the operation of the website.
* Not upload or transmit malicious software, viruses, or harmful code.
* Respect the intellectual property rights of Astronava and third parties.

If you submit birth details relating to another person, you represent that you have obtained the necessary permission to do so.

---

# 4. Astrology Services

Astronava generates reports using traditional Vedic astrology principles and the birth information provided by users.

The quality and accuracy of any report depend on the accuracy of the information entered.

Astronava does not guarantee the accuracy, completeness, or suitability of any astrological interpretation for a particular purpose.

---

# 5. No Professional Advice

The content available on Astronava, including predictions, compatibility reports, gemstone recommendations, remedies, articles, and other materials, is provided solely for informational and educational purposes.

Nothing on this website should be interpreted as:

* Medical advice
* Legal advice
* Financial or investment advice
* Psychological advice
* Professional counselling

You should consult qualified professionals before making important personal, financial, legal, or medical decisions.

---

# 6. Intellectual Property

Unless otherwise stated, all content available on Astronava, including but not limited to:

* Website design
* Logos
* Branding
* Text
* Graphics
* Icons
* Software
* Source code (excluding third-party open-source components)
* Databases
* Astrological calculations
* Original content

is the property of Astronava and is protected by applicable intellectual property laws.

You may not copy, reproduce, distribute, modify, or commercially exploit any content without prior written permission.

---

# 7. Acceptable Use

You agree not to:

* Attempt to hack or compromise the website.
* Reverse engineer or exploit our services.
* Use automated tools to scrape website content without permission.
* Circumvent security measures.
* Use the platform for unlawful or fraudulent activities.
* Distribute malware or harmful software.

Violation of these Terms may result in suspension or permanent restriction of access to the website.

---

# 8. Third-Party Services

Astronava may rely on third-party providers, including hosting, analytics, and cloud infrastructure services.

We are not responsible for the availability, policies, or practices of third-party services.

---

# 9. Service Availability

We strive to provide reliable access to our website; however, we do not guarantee uninterrupted, error-free, or continuous availability.

We reserve the right to modify, suspend, discontinue, or remove any feature or service at any time without prior notice.

---

# 10. Limitation of Liability

To the maximum extent permitted by applicable law, Astronava, its owners, developers, affiliates, and contributors shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising out of or relating to:

* Your use of the website.
* Your reliance on astrological reports or interpretations.
* Errors or interruptions in the service.
* Temporary or permanent unavailability of the website.
* Unauthorized access to or alteration of your data.

Your use of Astronava is entirely at your own risk.

---

# 11. Indemnification

You agree to indemnify and hold harmless Astronava, its owners, developers, affiliates, and partners from any claims, liabilities, damages, costs, or expenses arising from your misuse of the website or violation of these Terms.

---

# 12. Privacy

Your use of Astronava is also governed by our **Privacy Policy**, which explains how we collect, use, and protect your information.

---

# 13. Changes to These Terms

We may update these Terms from time to time to reflect changes in our services, legal obligations, or operational practices.

The updated version will become effective immediately upon publication on this page.

Continued use of the website after any changes constitutes acceptance of the revised Terms.

---

# 14. Governing Law

These Terms & Conditions shall be governed by and interpreted in accordance with the laws of **India**, without regard to its conflict of law principles.

Any disputes arising from the use of Astronava shall be subject to the exclusive jurisdiction of the competent courts in India.

---

# 15. Contact Us

If you have any questions regarding these Terms & Conditions, please contact us:

**Email:** [himaaghna@gmail.com](mailto:himaaghna@gmail.com)

**Website:** https://astronava.vercel.app

---

Thank you for using **Astronava**.`;

export const PRIVACY_POLICY_CONTENT = `# Privacy Policy

**Effective Date:** September 2026

Welcome to **Astronava** ("Astronava", "we", "our", or "us"). We respect your privacy and are committed to protecting your personal information.

This Privacy Policy explains what information we collect, how we use it, how long we retain it, and your rights when using our website.

By accessing or using Astronava, you acknowledge that you have read and understood this Privacy Policy.

---

## Emergency Mental Health Notice

Astronava is **not** a crisis intervention service, mental health provider, or emergency support service.

If you are experiencing emotional distress, thoughts of self-harm, suicidal thoughts, or believe you may be in immediate danger, **do not rely on this website or any astrological guidance**. Please seek immediate assistance from your local emergency services, a qualified mental health professional, or a trusted family member or friend.

If you believe someone else may be at immediate risk, contact your local emergency services without delay.

The content and services provided by Astronava are **not intended to diagnose, treat, or prevent any mental health condition**, and should never be used as a substitute for professional medical or psychological care.

---

# 1. Information We Collect

Most features of Astronava can be accessed without creating an account.

For our **Match Finder (Kundali Milan)** feature, we collect the following information for **both Partner 1 and Partner 2**:

* Name
* Gender
* Date of Birth
* Birth Time (including AM/PM)
* Birth Place

This information is provided voluntarily by users for the purpose of generating astrological compatibility reports.

---

# 2. Information We Do Not Collect

At this time, Astronava does **not** collect or require:

* Phone numbers
* Government-issued identification
* Postal addresses
* Payment information
* Bank or card details

If paid services are introduced in the future, this Privacy Policy will be updated accordingly.

---

# 3. Purpose of Data Collection

We collect personal information only to:

* Generate Kundali Milan (Match Finder) compatibility reports
* Perform Vedic astrology calculations requested by users
* Improve the reliability and performance of our services
* Detect abuse, spam, or misuse of the platform
* Maintain the security and integrity of our systems

We do **not** sell or rent your personal information.

---

# 4. Data Retention

Match Finder information is stored securely on our servers for **up to 24 hours**.

After this period, the data is **automatically deleted** from our systems.

Please note that temporary server logs or backup systems may retain limited technical information for security or disaster recovery purposes where required.

---

# 5. Legal Basis for Processing

By submitting birth details through the Match Finder feature, you consent to the processing of that information for generating the requested astrological compatibility report.

If you submit information relating to another individual, you confirm that you have the necessary permission or authority to provide that information.

---

# 6. Cookies and Similar Technologies

Astronava may use essential cookies or similar technologies to:

* Maintain website functionality
* Improve website performance
* Enhance user experience
* Prevent abuse and unauthorized access

These cookies do not identify you personally.

---

# 7. Third-Party Services

To operate our website, we may use trusted third-party providers, including:

* Vercel (Website Hosting)
* Firebase (Backend and Database Services)
* Google Analytics (Website Analytics)

These providers may process limited technical information necessary to provide their services.

---

# 8. Data Security

We implement reasonable administrative, technical, and organizational measures to safeguard the information we collect.

While we strive to protect your information, no method of electronic transmission or storage is completely secure. Accordingly, we cannot guarantee absolute security.

---

# 9. Children's Privacy

Astronava is not intended for children under the age of 13.

We do not knowingly collect personal information from children.

If you believe that a child has provided personal information through our website, please contact us so that appropriate action can be taken.

---

# 10. Your Rights

Subject to applicable law, you may have the right to:

* Request information about the personal data we process
* Request correction of inaccurate information
* Request deletion of your personal information where applicable
* Contact us regarding any privacy concerns

Requests may be submitted using the contact information provided below.

---

# 11. Changes to this Privacy Policy

We may update this Privacy Policy from time to time to reflect changes in our services, legal requirements, or operational practices.

The updated version will be published on this page with a revised Effective Date.

---

# 12. Contact Us

If you have any questions about this Privacy Policy or the way your information is handled, please contact us:

**Email:** [himaaghna@gmail.com](mailto:himaaghna@gmail.com)

**Website:** https://astronava.vercel.app

---

Thank you for trusting **Astronava**.`;

export const CONTACT_INFO = {
  email: 'himaaghna@gmail.com',
  website: 'https://astronava.vercel.app',
  developerName: 'Himaghna Medhi',
  twitter: 'https://x.com/himaghnamedhi',
  effectiveDate: 'September 2026',
};
